import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import './globals.css';

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


import type { Metadata } from 'next';

import Layout from '@/components/Layout';
import { AuthContextProvider } from '@/context/AuthContext';
import { UIContextProvider } from '@/context/UIContext';

export const metadata: Metadata = {
  title: 'Budget Planner',
  // TODO: update description + add favicon
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body    className={cn(
          "min-h-screen dark font-sans antialiased ",
          fontSans.variable
        )}
      >
        <UIContextProvider>
          <AuthContextProvider>
            <Layout>{children}</Layout>
          </AuthContextProvider>
        </UIContextProvider>
      </body>
    </html>
  );
}
