import './globals.css';

import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';

import Providers from './providers';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

import type { Metadata } from 'next';

import Layout from '@/components/Layout';

export const metadata: Metadata = {
  title: 'Budget Planner',
  // TODO: update description + add favicon
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="box-border">
      <body
        className={cn(
          'min-h-screen font-sans antialiased border-x-inherit relative pb-24',
          fontSans.variable,
        )}
      >
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
